apiVersion: project.openshift.io/v1
kind: Project
metadata:
     name: test-case2
     annotations:
       argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,ServerSideApply=true,ApplyOutOfSyncOnly=true
       openshift.io/display-name: "test1"
       openshift.io/description: "test1"
spec:
    finalizers:
    - kubernetes
